import { formatDateTime, formatExportValue } from '@/lib/export/format'
import type { ExportColumn, ExportDataset } from '@/lib/export/types'
import { PrintToolbar } from './print-toolbar'

/**
 * Beyond this many columns an A4 portrait sheet starts truncating, so the
 * document turns itself landscape. Measured against the completion-history
 * table, which is the widest one the app has at 14 columns.
 */
const LANDSCAPE_COLUMN_THRESHOLD = 8

function printColumns<T>(columns: ExportColumn<T>[]): ExportColumn<T>[] {
  return columns.filter((column) => column.only !== 'csv')
}

interface PrintDocumentProps<T> {
  dataset: ExportDataset<T>
  csvHref: string
  /** Rendered where "no rows matched" needs to say something specific. */
  emptyMessage?: string
}

export function PrintDocument<T>({ dataset, csvHref, emptyMessage }: PrintDocumentProps<T>) {
  const columns = printColumns(dataset.columns)
  const landscape = columns.length > LANDSCAPE_COLUMN_THRESHOLD
  const exportedAt = formatDateTime(new Date())

  const identity = [dataset.title, dataset.subtitle, `Exported ${exportedAt}`]
    .filter(Boolean)
    .join('  ·  ')

  return (
    <div className="pd-shell">
      <PrintToolbar
        csvHref={csvHref}
        title={dataset.title}
        rowCount={dataset.rows.length}
        truncated={Boolean(dataset.truncated)}
      />

      <article className={landscape ? 'pd pd--landscape' : 'pd'}>
        <header className="pd-head">
          <div>
            <h1 className="pd-head__title">{dataset.title}</h1>
            {dataset.subtitle ? <p className="pd-head__subtitle">{dataset.subtitle}</p> : null}
          </div>
          <div className="pd-head__brand">
            <span className="pd-head__brandname">NeatPlan</span>
            {exportedAt}
          </div>
        </header>

        {dataset.filters.length > 0 ? (
          <ul className="pd-context">
            {dataset.filters.map((filter) => (
              <li key={`${filter.label}-${filter.value}`}>
                <span className="pd-context__label">{filter.label}</span>
                <span className="pd-context__value">{filter.value}</span>
              </li>
            ))}
          </ul>
        ) : null}

        {dataset.summary && dataset.summary.length > 0 ? (
          <div className="pd-stats">
            {dataset.summary.map((stat) => (
              <div className="pd-stat" key={stat.label}>
                <span className="pd-stat__label">{stat.label}</span>
                <span className="pd-stat__value">{stat.value}</span>
              </div>
            ))}
          </div>
        ) : null}

        {dataset.truncated ? (
          <p className="pd-notice">
            Showing the first {dataset.truncated.cap.toLocaleString()} of{' '}
            {dataset.truncated.total.toLocaleString()} matching rows. Narrow the filters and export
            again to see the rest.
          </p>
        ) : null}

        <div className="pd-tablewrap">
          {dataset.rows.length === 0 ? (
            <p className="pd-empty">{emptyMessage ?? 'Nothing matched these filters.'}</p>
          ) : (
            <table className="pd-table">
              <colgroup>
                {columns.map((column) => (
                  <col key={column.key} style={{ width: `${((column.width ?? 1) / totalWidth(columns)) * 100}%` }} />
                ))}
              </colgroup>
              <thead>
                <tr>
                  {columns.map((column) => (
                    <th key={column.key} scope="col" className={column.align === 'right' ? 'pd-num' : undefined}>
                      {column.header}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {dataset.rows.map((row, index) => (
                  <tr key={index}>
                    {columns.map((column, columnIndex) => (
                      <td
                        key={column.key}
                        className={[
                          column.align === 'right' ? 'pd-num' : '',
                          column.wrap ? 'pd-wrap' : '',
                          // The first column is the row's identity - the anchor
                          // the eye scans down a printed sheet.
                          columnIndex === 0 ? 'pd-identity' : '',
                        ]
                          .filter(Boolean)
                          .join(' ') || undefined}
                      >
                        {formatExportValue(column.value(row))}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>

        <footer className="pd-foot">
          <span>{dataset.note ?? 'Generated by NeatPlan.'}</span>
          <span>
            {dataset.rows.length.toLocaleString()} {dataset.rows.length === 1 ? 'row' : 'rows'}
          </span>
        </footer>
      </article>

      {/* Repeats on every printed sheet so a loose page can be traced back. */}
      <div className="pd-runningfoot" aria-hidden="true">
        {identity}
      </div>
    </div>
  )
}

function totalWidth<T>(columns: ExportColumn<T>[]): number {
  return columns.reduce((sum, column) => sum + (column.width ?? 1), 0)
}
